"""recreate generic queue requests

Revision ID: 2740f47ba7ef
Revises: 20260207_purge_generic
Create Date: 2026-02-07 17:00:08.702134

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20260207_002"
down_revision = "20260207_001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum type properly
    queuestatus_enum = sa.Enum(
        "PENDING", "IN_PROGRESS", "COMPLETED", "FAILED", name="queuestatus"
    )
    queuestatus_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "queue_requests",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workflow_id", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "IN_PROGRESS", "COMPLETED", "FAILED", name="queuestatus"
            ),
            nullable=True,
        ),
        sa.Column("progress_stage", sa.String(), nullable=True),
        sa.Column("progress_percentage", sa.Integer(), nullable=True),
        sa.Column("active_node_id", sa.String(), nullable=True),
        sa.Column("requestor_id", sa.Integer(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["requestor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_queue_requests_id"), "queue_requests", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_queue_requests_workflow_id"),
        "queue_requests",
        ["workflow_id"],
        unique=False,
    )
    op.drop_table("style_examples")
    op.alter_column(
        "agent_llm_mappings",
        "prompt_template_id",
        existing_type=sa.VARCHAR(length=36),
        comment="Reference to unified prompt_templates table",
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_prompt_template_history_change_type"),
        table_name="prompt_template_history",
    )
    op.drop_index(
        op.f("ix_prompt_template_history_changed_at"),
        table_name="prompt_template_history",
    )
    op.create_index(
        op.f("ix_prompt_template_history_id"),
        "prompt_template_history",
        ["id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("prompt_template_history_template_id_fkey"),
        "prompt_template_history",
        type_="foreignkey",
    )
    op.alter_column(
        "prompt_templates",
        "usage_count",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "prompt_templates",
        "success_rate",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "prompt_templates",
        "avg_latency_ms",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "prompt_templates",
        "avg_cost_usd",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "prompt_templates",
        "avg_output_tokens",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "prompt_templates",
        "is_experimental",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "prompt_templates",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "prompt_templates",
        "created_at_datetime",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("ix_prompt_templates_agent_active"), table_name="prompt_templates"
    )
    op.drop_index(op.f("ix_prompt_templates_is_active"), table_name="prompt_templates")
    op.drop_index(
        op.f("ix_prompt_templates_template_name"), table_name="prompt_templates"
    )
    op.create_index(
        op.f("ix_prompt_templates_id"), "prompt_templates", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prompt_templates_id"), table_name="prompt_templates")
    op.create_index(
        op.f("ix_prompt_templates_template_name"),
        "prompt_templates",
        ["template_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prompt_templates_is_active"),
        "prompt_templates",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prompt_templates_agent_active"),
        "prompt_templates",
        ["agent_id", "is_active"],
        unique=False,
    )
    op.alter_column(
        "prompt_templates",
        "created_at_datetime",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "prompt_templates",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "prompt_templates",
        "is_experimental",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "prompt_templates",
        "avg_output_tokens",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "prompt_templates",
        "avg_cost_usd",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "prompt_templates",
        "avg_latency_ms",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "prompt_templates",
        "success_rate",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "prompt_templates",
        "usage_count",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.create_foreign_key(
        op.f("prompt_template_history_template_id_fkey"),
        "prompt_template_history",
        "prompt_templates",
        ["template_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        op.f("ix_prompt_template_history_id"), table_name="prompt_template_history"
    )
    op.create_index(
        op.f("ix_prompt_template_history_changed_at"),
        "prompt_template_history",
        ["changed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prompt_template_history_change_type"),
        "prompt_template_history",
        ["change_type"],
        unique=False,
    )
    op.alter_column(
        "agent_llm_mappings",
        "prompt_template_id",
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment="Reference to unified prompt_templates table",
        existing_nullable=True,
    )
    op.create_table(
        "style_examples",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("question_text", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "question_category", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column("domain_context", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("ai_draft", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("human_final", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("diff_summary", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "similarity_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("embedding_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("style_examples_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("style_examples_pkey")),
    )
    op.drop_index(op.f("ix_queue_requests_workflow_id"), table_name="queue_requests")
    op.drop_index(op.f("ix_queue_requests_id"), table_name="queue_requests")
    op.drop_table("queue_requests")
    # ### end Alembic commands ###
