"""fix_prompt_templates_schema_mismatch

Revision ID: 54b988b99635
Revises: 20260204_add_langfuse_config
Create Date: 2026-02-04 08:29:03.990348

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20260204_002"
down_revision = "20260204_001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "langfuse_config",
        "enabled",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "langfuse_config",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "langfuse_config",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_langfuse_config_enabled"), table_name="langfuse_config")
    # op.add_column(
    #     "prompt_template_history",
    #     sa.Column("agent_id", sa.String(length=100), nullable=False),
    # )
    # op.add_column(
    #     "prompt_template_history",
    #     sa.Column("changed_at", sa.DateTime(), nullable=False),
    # )
    # op.alter_column(
    #     "prompt_template_history",
    #     "new_content",
    #     existing_type=sa.TEXT(),
    #     nullable=False,
    # )
    # op.create_index(
    #     op.f("ix_prompt_template_history_agent_id"),
    #     "prompt_template_history",
    #     ["agent_id"],
    #     unique=False,
    # )
    # op.create_index(
    #     op.f("ix_prompt_template_history_id"),
    #     "prompt_template_history",
    #     ["id"],
    #     unique=False,
    # )
    # op.drop_constraint(
    #     op.f("prompt_template_history_template_id_fkey"),
    #     "prompt_template_history",
    #     type_="foreignkey",
    # )
    # op.drop_column("prompt_template_history", "new_version")
    # op.drop_column("prompt_template_history", "old_version")
    # op.drop_column("prompt_template_history", "metadata")
    # op.drop_column("prompt_template_history", "created_at")
    # op.add_column(
    #     "prompt_templates", sa.Column("description", sa.Text(), nullable=True)
    # )
    # op.add_column(
    #     "prompt_templates", sa.Column("avg_output_tokens", sa.Integer(), nullable=True)
    # )
    # op.add_column(
    #     "prompt_templates", sa.Column("is_experimental", sa.Boolean(), nullable=True)
    # )
    # op.add_column(
    #     "prompt_templates",
    #     sa.Column("experiment_id", sa.String(length=100), nullable=True),
    # )
    # op.add_column(
    #     "prompt_templates",
    #     sa.Column("control_version_id", sa.String(length=36), nullable=True),
    # )
    # op.add_column(
    #     "prompt_templates",
    #     sa.Column("created_at_datetime", sa.DateTime(), nullable=True),
    # )
    # op.add_column(
    #     "prompt_templates",
    #     sa.Column("previous_version_id", sa.String(length=36), nullable=True),
    # )
    # op.add_column(
    #     "prompt_templates", sa.Column("rollback_reason", sa.Text(), nullable=True)
    # )
    # op.alter_column(
    #     "prompt_templates",
    #     "tags",
    #     existing_type=postgresql.ARRAY(sa.TEXT()),
    #     type_=sa.JSON(),
    #     existing_nullable=True,
    #     postgresql_using="to_json(tags)",
    # )
    # op.alter_column(
    #     "prompt_templates",
    #     "parameters",
    #     existing_type=postgresql.JSONB(astext_type=sa.Text()),
    #     type_=sa.JSON(),
    #     existing_nullable=True,
    # )
    # op.alter_column(
    #     "prompt_templates",
    #     "usage_count",
    #     existing_type=sa.INTEGER(),
    #     nullable=True,
    #     existing_server_default=sa.text("0"),
    # )
    # op.alter_column(
    #     "prompt_templates",
    #     "success_rate",
    #     existing_type=sa.DOUBLE_PRECISION(precision=53),
    #     type_=sa.Integer(),
    #     existing_nullable=True,
    # )
    # op.alter_column(
    #     "prompt_templates",
    #     "avg_latency_ms",
    #     existing_type=sa.DOUBLE_PRECISION(precision=53),
    #     type_=sa.Integer(),
    #     existing_nullable=True,
    # )
    # op.alter_column(
    #     "prompt_templates",
    #     "avg_cost_usd",
    #     existing_type=sa.DOUBLE_PRECISION(precision=53),
    #     type_=sa.Integer(),
    #     existing_nullable=True,
    # )
    # op.alter_column(
    #     "prompt_templates",
    #     "created_at",
    #     existing_type=postgresql.TIMESTAMP(timezone=True),
    #     type_=sa.DateTime(),
    #     nullable=False,
    #     existing_server_default=sa.text("now()"),
    # )
    # op.alter_column(
    #     "prompt_templates",
    #     "updated_at",
    #     existing_type=postgresql.TIMESTAMP(timezone=True),
    #     type_=sa.DateTime(),
    #     existing_nullable=True,
    #     existing_server_default=sa.text("now()"),
    # )
    # op.drop_index(
    #     op.f("ix_prompt_templates_agent_active"), table_name="prompt_templates"
    # )
    # op.drop_index(op.f("ix_prompt_templates_is_active"), table_name="prompt_templates")
    # op.drop_constraint(
    #     op.f("prompt_templates_agent_id_template_name_version_key"),
    #     "prompt_templates",
    #     type_="unique",
    # )
    # op.create_index(
    #     op.f("ix_prompt_templates_experiment_id"),
    #     "prompt_templates",
    #     ["experiment_id"],
    #     unique=False,
    # )
    # op.create_index(
    #     op.f("ix_prompt_templates_id"), "prompt_templates", ["id"], unique=False
    # )
    # op.drop_column("prompt_templates", "ab_test_id")
    # op.drop_column("prompt_templates", "ab_test_variant")
    op.alter_column(
        "reviews", "reviewer_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("reviews", "reviewer_id", existing_type=sa.INTEGER(), nullable=True)
    op.add_column(
        "prompt_templates",
        sa.Column(
            "ab_test_variant", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prompt_templates",
        sa.Column(
            "ab_test_id", sa.VARCHAR(length=36), autoincrement=False, nullable=True
        ),
    )
    op.drop_index(op.f("ix_prompt_templates_id"), table_name="prompt_templates")
    op.drop_index(
        op.f("ix_prompt_templates_experiment_id"), table_name="prompt_templates"
    )
    op.create_unique_constraint(
        op.f("prompt_templates_agent_id_template_name_version_key"),
        "prompt_templates",
        ["agent_id", "template_name", "version"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_prompt_templates_is_active"),
        "prompt_templates",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prompt_templates_agent_active"),
        "prompt_templates",
        ["agent_id", "is_active"],
        unique=False,
    )
    op.alter_column(
        "prompt_templates",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "prompt_templates",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "prompt_templates",
        "avg_cost_usd",
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "prompt_templates",
        "avg_latency_ms",
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "prompt_templates",
        "success_rate",
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "prompt_templates",
        "usage_count",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "prompt_templates",
        "parameters",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "prompt_templates",
        "tags",
        existing_type=sa.JSON(),
        type_=postgresql.ARRAY(sa.TEXT()),
        existing_nullable=True,
    )
    op.drop_column("prompt_templates", "rollback_reason")
    op.drop_column("prompt_templates", "previous_version_id")
    op.drop_column("prompt_templates", "created_at_datetime")
    op.drop_column("prompt_templates", "control_version_id")
    op.drop_column("prompt_templates", "experiment_id")
    op.drop_column("prompt_templates", "is_experimental")
    op.drop_column("prompt_templates", "avg_output_tokens")
    op.drop_column("prompt_templates", "description")
    op.add_column(
        "prompt_template_history",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "prompt_template_history",
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "prompt_template_history",
        sa.Column("old_version", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prompt_template_history",
        sa.Column("new_version", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("prompt_template_history_template_id_fkey"),
        "prompt_template_history",
        "prompt_templates",
        ["template_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        op.f("ix_prompt_template_history_id"), table_name="prompt_template_history"
    )
    op.drop_index(
        op.f("ix_prompt_template_history_agent_id"),
        table_name="prompt_template_history",
    )
    op.alter_column(
        "prompt_template_history", "new_content", existing_type=sa.TEXT(), nullable=True
    )
    op.drop_column("prompt_template_history", "changed_at")
    op.drop_column("prompt_template_history", "agent_id")
    op.create_index(
        op.f("ix_langfuse_config_enabled"), "langfuse_config", ["enabled"], unique=False
    )
    op.alter_column(
        "langfuse_config",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "langfuse_config",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "langfuse_config",
        "enabled",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    # ### end Alembic commands ###
